print("Tigre")
print("Washington Alves")
print("21 anos de idade")
print(2023)
print(1+2)
print()
print(4-2)
print()
print(5*2)
print()
print(10/2)
print()
print("Me chamo Washington Alves, tenho 21 anos de idade, estou no ano de 2023 e estou começando a aprender programação")
print()
print("x=25*4")
print ()
print(11/2)
print ()
print(type("21 anos"))
print(type("Washington"))